FROM python:3.12.1

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY . .
RUN pip install --upgrade pip && pip install -r requirements.txt

CMD ["celery", "-A", "src.libs.celery_app", "worker", "-l", "info", "-P", "gevent"]
