"""empty message

Revision ID: 68bf76c670ef
Revises: 8bdb7c0b9e51
Create Date: 2025-05-12 17:38:55.271903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68bf76c670ef'
down_revision: Union[str, None] = '8bdb7c0b9e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brands', 'name',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('fabric_mappings', 'fabric_id_JV',
               existing_type=sa.INTEGER(),
               comment='Fabric ID from the JV source system, references fabrics.id',
               existing_nullable=True)
    op.alter_column('fabric_mappings', 'fabric_id_XL',
               existing_type=sa.INTEGER(),
               comment='Fabric ID from the XL source system, references fabrics.id',
               existing_nullable=True)
    op.create_index('ix_fabric_mapping_jv_id', 'fabric_mappings', ['fabric_id_JV'], unique=False)
    op.create_index('ix_fabric_mapping_xl_id', 'fabric_mappings', ['fabric_id_XL'], unique=False)
    op.create_unique_constraint('uq_fabric_mapping_pair', 'fabric_mappings', ['fabric_id_JV', 'fabric_id_XL'])
    op.create_table_comment(
        'fabric_mappings',
        'Stores mappings between fabric IDs from JV and XL systems',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint(None, 'fabrics', ['afterbuy_id'])
    op.drop_constraint('products_mappings_id_key', 'products_mappings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_mappings_id_key', 'products_mappings', ['id'])
    op.drop_constraint(None, 'fabrics', type_='unique')
    op.drop_table_comment(
        'fabric_mappings',
        existing_comment='Stores mappings between fabric IDs from JV and XL systems',
        schema=None
    )
    op.drop_constraint('uq_fabric_mapping_pair', 'fabric_mappings', type_='unique')
    op.drop_index('ix_fabric_mapping_xl_id', table_name='fabric_mappings')
    op.drop_index('ix_fabric_mapping_jv_id', table_name='fabric_mappings')
    op.alter_column('fabric_mappings', 'fabric_id_XL',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Fabric ID from the XL source system, references fabrics.id',
               existing_nullable=True)
    op.alter_column('fabric_mappings', 'fabric_id_JV',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Fabric ID from the JV source system, references fabrics.id',
               existing_nullable=True)
    op.alter_column('brands', 'name',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=600),
               existing_nullable=False)
    # ### end Alembic commands ###
