"""empty message

Revision ID: 887c39f577ba
Revises: 68bf76c670ef
Create Date: 2025-05-14 16:41:32.659968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887c39f577ba'
down_revision: Union[str, None] = '68bf76c670ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fabrics', sa.Column('total_count', sa.Integer(), nullable=True))
    op.add_column('fabrics', sa.Column('parsed_count', sa.Integer(), nullable=True))
    op.drop_column('fabrics', 'items_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fabrics', sa.Column('items_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('fabrics', 'parsed_count')
    op.drop_column('fabrics', 'total_count')
    # ### end Alembic commands ###
