"""empty message

Revision ID: 8bdb7c0b9e51
Revises: ed0947cd5c82
Create Date: 2025-04-17 15:32:21.999105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bdb7c0b9e51'
down_revision: Union[str, None] = 'ed0947cd5c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'brands', ['id'])
    op.create_unique_constraint(None, 'fabric_mappings', ['id'])
    op.drop_constraint('fabric_mappings_fabric_id_JV_fkey', 'fabric_mappings', type_='foreignkey')
    op.drop_constraint('fabric_mappings_fabric_id_XL_fkey', 'fabric_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'fabric_mappings', 'fabrics', ['fabric_id_JV'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fabric_mappings', 'fabrics', ['fabric_id_XL'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'fabrics', ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    op.create_unique_constraint(None, 'products_mappings', ['id'])
    op.drop_constraint('products_mappings_fabric_mapping_id_fkey', 'products_mappings', type_='foreignkey')
    op.drop_constraint('products_mappings_xl_product_id_fkey', 'products_mappings', type_='foreignkey')
    op.drop_constraint('products_mappings_jv_product_id_fkey', 'products_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'products_mappings', 'products', ['xl_product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products_mappings', 'products', ['jv_product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products_mappings', 'fabric_mappings', ['fabric_mapping_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'urls', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'urls', type_='unique')
    op.drop_constraint(None, 'products_mappings', type_='foreignkey')
    op.drop_constraint(None, 'products_mappings', type_='foreignkey')
    op.drop_constraint(None, 'products_mappings', type_='foreignkey')
    op.create_foreign_key('products_mappings_jv_product_id_fkey', 'products_mappings', 'products', ['jv_product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('products_mappings_xl_product_id_fkey', 'products_mappings', 'products', ['xl_product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('products_mappings_fabric_mapping_id_fkey', 'products_mappings', 'fabric_mappings', ['fabric_mapping_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'products_mappings', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'fabrics', type_='unique')
    op.drop_constraint(None, 'fabric_mappings', type_='foreignkey')
    op.drop_constraint(None, 'fabric_mappings', type_='foreignkey')
    op.create_foreign_key('fabric_mappings_fabric_id_XL_fkey', 'fabric_mappings', 'fabrics', ['fabric_id_XL'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fabric_mappings_fabric_id_JV_fkey', 'fabric_mappings', 'fabrics', ['fabric_id_JV'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'fabric_mappings', type_='unique')
    op.drop_constraint(None, 'brands', type_='unique')
    # ### end Alembic commands ###
